name: API Tests CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    services:
      docker:
        image: docker:dind
        ports:
          - 2375:2375
        options: --privileged

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker-compose build

    - name: Run Tests in Docker
      run: docker-compose run restful_booker_python_api_tests

    - name: Archive Test Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: allure-results

    - name: Install Python and Dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y python3 python3-pip
        pip3 install -r requirements.txt

    - name: Run Tests with pytest-html
      run: pytest --html=./reports/report.html

    - name: Archive HTML Report
      uses: actions/upload-artifact@v2
      with:
        name: html-report
        path: reports
