name: API Tests CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: master
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.5

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tests
        run: python -m unittest tests/auth/test_auth.py

      - name: Install pytest
        run: |
          pip install pytest-html

      - name: Run Tests with pytest-html
        run: python -m pytest -v --html=report.html

      - name: Archive HTML Report
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: ./report.html

      - name: SonarCloud Scan
        run: |
          # Install SonarScanner
          curl -o sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.0.2311-windows.zip
          tar -xf sonar-scanner.zip -C C:\
          
          # Set up environment variable
          $env:SONAR_SCANNER_HOME = "C:\sonar-scanner-4.6.0.2311-windows"
          
          # Run SonarScanner analysis
          & "$env:SONAR_SCANNER_HOME\bin\sonar-scanner.bat" -D"sonar.projectKey=SeveR-ina_restful_booker_python_api_tests" -D"sonar.sources=." -D"sonar.host.url=https://sonarcloud.io" -D"sonar.login=${{ secrets.SONAR_TOKEN }}" -D"sonar.organization=${{ secrets.SONAR_ORGANIZATION }}"

        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build Docker Image
        run: docker-compose build

      - name: Run Tests in Docker
        run: docker-compose run restful_booker_python_api_tests

      - name: Archive Test Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: allure_results

