name: API Tests CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        # Specify ref explicitly to avoid warning about Node.js 12
        ref: master
        persist-credentials: false  # Ensure this line is present

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4  # Specify the version you need

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Tests
      run: python -m unittest test_auth.py

    - name: Install pytest
      run: |
        pip install pytest-html

    - name: Run Tests with pytest-html
      run: pytest -v --html=report.html

    - name: Archive HTML Report
      uses: actions/upload-artifact@v2
      with:
        name: html-report
        path: /report.html

#    - name: Build Docker Image
#      run: docker-compose build
#
#    - name: Run Tests in Docker
#      run: docker-compose run restful_booker_python_api_tests
#
#    - name: Archive Test Artifacts
#      uses: actions/upload-artifact@v2
#      with:
#        name: test-results
#        path: allure-results
